// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOH5g_hgpPl1vljZ_J2C_1HZulUaDlFMM',
    appId:   '1:978588878352:web:5e773748c86d4ee00a2c95',
    messagingSenderId: '978588878352',
    projectId: 'boombim-makerstar',
    authDomain: 'boombim-makerstar.firebaseapp.com',
    storageBucket: 'boombim-makerstar.appspot.com',
    measurementId: 'G-0RQB23GCG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHZltK3rSLoN0SMBisA6nimBhzR5KaDzc',
    appId: '1:978588878352:android:6aed033d8c8c5e9d0a2c95',
    messagingSenderId: '978588878352',
    projectId: 'boombim-makerstar',
    storageBucket: 'boombim-makerstar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA0MNbXhyGHvLpDcjpe-t7_mX6ILn9jI4',
    appId: '1:978588878352:ios:8e842b120ba4430e0a2c95',
    messagingSenderId: '978588878352',
    projectId: 'boombim-makerstar',
    storageBucket: 'boombim-makerstar.appspot.com',
    iosClientId: '978588878352-p35r3fpbe43fpmchu1lnhhq0g8866c6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.boombimMakerstar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA0MNbXhyGHvLpDcjpe-t7_mX6ILn9jI4',
    appId: '1:978588878352:ios:b69951b4a2de5de10a2c95',
    messagingSenderId: '978588878352',
    projectId: 'boombim-makerstar',
    storageBucket: 'boombim-makerstar.appspot.com',
    iosClientId: '978588878352-3onbnq3phid7hrsqtn38le51kppc8rra.apps.googleusercontent.com',
    iosBundleId: 'com.example.boombimMakerstar.RunnerTests',
  );
}
